---
  block:
    - name: Start Munge service
      service: name=munge state=started
      register: munge_installed
      ignore_errors: yes

    - name: Include "{{ansible_os_family}}" munge recipe if package is not present
      include: "{{ansible_os_family}}.yaml"
      when: munge_installed is not defined or munge_installed.failed

    - name: Register munge key
      stat: path=/etc/munge/munge.key
      register: munge_key

    - name: set munge log directory access rights
      file: path=/var/log/munge state=directory mode=0700

    - name: set munge run directory access rights
      file: path=/var/run/munge state=directory mode=0700 owner=munge group=munge

    - name: set munge key contents
      file: path=/etc/munge/munge.key owner=munge group=munge contents="{{ munge_key }}" mode=0600
      notify: restart munge
  become: yes