---
- block:
  - name: Start Munge service
    service: name=munge state=started
    register: munge_installed
    ignore_errors: yes

  - name: Install munge (Debian)
    block:
      - name: Install munge
        apt: name=munge update_cache=yes cache_valid_time=3600
        register: munge_install

      - name: Delete /etc/munge/munge.key created in munge installation
        file: path=/etc/munge/munge.key state=absent
        when: munge_install.changed
    when: ansible_os_family == "Debian"

  - name: Install munge (RedHat)
    block:
      - name: Yum install epel
        yum: name=epel-release

      - name: Yum install munge
        yum: name=munge,munge-devel

      - block:
        - name: Yum install packages for Centos 6
          yum: name=libselinux-python

        # Fix for centos 6 due to socket errors
        - name: Create munge config file
          copy:
            content: 'OPTIONS="--force"'
            dest: /etc/default/munge
            force: no
            group: root
            owner: root
            mode: 0644
        when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 6
    when: ansible_os_family == "RedHat"

  # - name: Register munge key
  #   stat: path=/etc/munge/munge.key
  #   register: munge_key

  - name: set munge log directory access rights
    file: path=/var/log/munge state=directory mode=0700

  - name: set munge run directory access rights
    file: path=/var/run/munge state=directory mode=0755 owner=munge group=munge

  - name: set munge key contents
    copy: dest=/etc/munge/munge.key owner=munge group=munge content="{{ munge_key }}" mode=0600
    notify: restart munge
    when: not munge_key_is_b64encoded

  - name: set munge key contents (b64encoded)
    shell: base64 -d >/etc/munge/munge.key && chown munge:munge /etc/munge/munge.key && chmod 0600 /etc/munge/munge.key
    args:
      stdin: "{{ munge_key }}"
    notify: restart munge
    when: munge_key_is_b64encoded

  become: true
  become_user: root